version: '3.2'

services:

  mariadb:
    container_name: mariadb
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: bot
      MARIADB_PASSWORD: bot
      MARIADB_DATABASE: bot
      TZ: Europe/Rome
    restart: unless-stopped
    volumes:
      - type: volume
        source: mariadb_volume
        target: /var/lib/mysql

  menu_scraper_bot:
    build: .
    container_name: menu_scraper_bot
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DOCKER: "True"
      SECRETS: /run/secrets/secrets
      COOKIES: /run/secrets/cookies
    secrets:
      - secrets
      - cookies

secrets:
    secrets:
        file: ./secrets.json
    cookies:
        file: ./cookies.json

volumes:
  mariadb_volume:



