version: '3.2'

services:

  mariadb-dev:
    container_name: mariadb-dev
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: bot
      MARIADB_PASSWORD: bot
      MARIADB_DATABASE: bot
      TZ: Europe/Rome
    restart: unless-stopped
    volumes:
      - type: volume
        source: mariadb_volume
        target: /data

  menu_scraper_bot:
    build: .
    container_name: menu_scraper_bot
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      SECRETS: /run/secrets/secrets
    secrets:
      - secrets

secrets:
    secrets:
        file: ./secrets.json

volumes:
  mariadb_volume:



